# Generated by Django 4.0.6 on 2022-07-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_comment_posted_at_alter_post_liked_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
