# Generated by Django 4.0.6 on 2022-08-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_connections_followers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
